# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Ignacio Contreras Zúñiga
email: iscontreras@uc.cl
description: Academic website of Ignacio Contreras Zúñiga
baseurl: ""
url: "https://ignacontreras.github.io"
affiliation:
og_image: /assets/img/profile-pic.jpg

header:
  pages:
    - name: Home
      slug: /
    - name: Publications
    - name: Blog

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: iscontreras@uc.cl
      link: mailto:iscontreras@uc.cl
  follow:
    - name: LinkedIn
      link: https://www.linkedin.com/in/ignacio-contreras-z%C3%BA%C3%B1iga/
  
# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
